name: CI Pipeline

on: [push, pull_request]  # Runs on every push and PR

jobs:
  test:
    runs-on: ubuntu-latest  # Uses Ubuntu as the environment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repo onto the vm before checking

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install Dependencies
        run: npm install  # Installs required packages

      - name: Run Linter
        run: npm run lint || true  # Ensures the pipeline doesn't fail

